# Generated by cpputils-cmake.
include /Volumes/Data/nn/build/CMakeFiles/nn.dir/flags.make
.PHONY: check-syntax
check-syntax:
	${CXX} -o /dev/null ${CXX_FLAGS} ${CXX_DEFINES} ${CXX_INCLUDES}  -S ${CHK_SOURCES}